<?php

namespace AppBundle\Repository\Antispam;

/**
 * AntispamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntispamRepository extends \Doctrine\ORM\EntityRepository
{
}
